# Generated by Django 6.1 on 2026-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer'), ('BUSINESS_BUYER', 'Business Buyer'), ('AGRO_DEALER', 'Agro Dealer')], default='BUYER', max_length=20),
        ),
    ]
