# Generated by Django 6.1 on 2026-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One-time Purchase'), ('WEEKLY', 'Weekly Subscription'), ('MONTHLY', 'Monthly Subscription')], default='ONE_TIME', max_length=20),
        ),
    ]
