# Generated by Django 6.1 on 2026-08-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit when threshold is met', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_price_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity for bulk pricing', max_digits=10, null=True),
        ),
    ]
