# Generated by Django 6.1 on 2026-08-14 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_governmentscheme_product_is_imperfect_agrimachinery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FERTILIZER', 'Fertilizer'), ('PESTICIDE', 'Pesticide / Medicine'), ('SEEDS', 'Seeds'), ('EQUIPMENT', 'Small Equipment')], default='FERTILIZER', max_length=20)),
                ('description', models.TextField()),
                ('usage_guidance', models.TextField(blank=True, help_text='How to use this product safely')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agro_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agro_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
